export default {
  powerCode: 'switch_led',
  colourCode: 'colour_data',
  workModeCode: 'work_mode',
  temperatureCode: 'temp_value',
  brightCode: 'bright_value',
  sceneCode: 'scene_data',
  musicCode: 'music_data',
  countdownCode: 'countdown',
  controlCode: 'control_data',
  autoCode: 'auto',
  readCode: 'read',
  setCode: 'countdown_set',
  leftCode: 'countdown_left',
};
